[language-server.llm-ls]
command = "llm-ls.sh"

[language-server.llm-ls.config]

[language-server.llm-ls.config.model]

# OpenAI-compatible provider
type = "open_ai"

# Your llama.cpp endpoint
chat_endpoint = "http://127.0.0.1:8080/v1/chat/completions"

# Replace with your model id
model = "qwen3b"

# Local server doesn't require authentication
[[language]]
name = "rust"
language-servers = [ "rust-analyzer", "llm-ls" ]

[[language]]
name = "cpp"
language-servers = [ "clangd", "llm-ls" ]
