[build]
rustflags = ["-C","target-cpu=x86-64-v3","-C","link-args=-Wl,-rpath=$ORIGIN/../lib"]
incremental = true

[profile.release]
opt-level = 3
debug = false
strip = true
overflow-checks = false
lto = true
incremental = true
rpath = false
