[build]
rustflags = ["-C","target-cpu=x86-64-v3"]
incremental = true

[profile.release]
inherits = "dev"
opt-level = 3
debug = false
strip = true
overflow-checks = false
lto = true
incremental = true
rpath = true
