[build]
rustflags = ["-C","target-cpu=x86-64-v3","-C","link-args=-Wl,-rpath=$ORIGIN/../lib64","-C","link-args=-Wl,--dynamic-linker=/var/tmp/RUST/lib64/ld-linux-x86-64.so.2"]
incremental = true

[profile.release]
opt-level = 3
debug = false
strip = true
overflow-checks = false
lto = true
incremental = true
rpath = false
