# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'infer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0binfer.proto\x12\x13myrdvideoinferinfer\"\x1d\n\rGrpcvideodata\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"9\n\x13Grpcvideoprediction\x12\n\n\x02pa\x18\x01 \x01(\x02\x12\n\n\x02pb\x18\x02 \x01(\x02\x12\n\n\x02pc\x18\x03 \x01(\x02\"S\n\x18Grpcvideopredictionreply\x12\x37\n\x05preds\x18\x01 \x03(\x0b\x32(.myrdvideoinferinfer.Grpcvideoprediction2n\n\x0cRdvideoinfer\x12^\n\x07\x44oinfer\x12\".myrdvideoinferinfer.Grpcvideodata\x1a-.myrdvideoinferinfer.Grpcvideopredictionreply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRPCVIDEODATA']._serialized_start=36
  _globals['_GRPCVIDEODATA']._serialized_end=65
  _globals['_GRPCVIDEOPREDICTION']._serialized_start=67
  _globals['_GRPCVIDEOPREDICTION']._serialized_end=124
  _globals['_GRPCVIDEOPREDICTIONREPLY']._serialized_start=126
  _globals['_GRPCVIDEOPREDICTIONREPLY']._serialized_end=209
  _globals['_RDVIDEOINFER']._serialized_start=211
  _globals['_RDVIDEOINFER']._serialized_end=321
# @@protoc_insertion_point(module_scope)
