FROM 4_python
COPY './important_functions.sh' '/root/important_functions.sh'
ENV CMAKE_PREFIX_PATH='/opt/venv/lib/python3.13/site-packages/torch/share/cmake'
ENV LIBTORCH='/opt/venv/lib/python3.13/site-packages/torch'
