#!/bin/sh
sudo apt update
sudo apt install \
    'automake' \
    'libevent-dev' \
    'yacc' \
    'libncurses-dev' \
    'build-essential' \
    'aria2' \
    'automake' \
    'bear' \
    'bison' \
    'build-essential' \
    'clang' \
    'clang-format' \
    'clang-tidy' \
    'clang-tools' \
    'clangd' \
    'cmake' \
    'curl' \
    'elfutils' \
    'ffmpeg' \
    'fish' \
    'fzf' \
    'g++' \
    'gawk' \
    'gcc' \
    'gettext' \
    'gettext-base' \
    'git' \
    'git-lfs' \
    'graphicsmagick-imagemagick-compat' \
    'ipython3' \
    'jq' \
    'libasound2-dev' \
    'libevent-dev' \
    'libfontconfig-dev' \
    'libgit2-dev' \
    'liblz4-dev' \
    'liblzo2-dev' \
    'libopencv-dev' \
    'libpcre2-16-0' \
    'libpcre2-32-0' \
    'libpcre2-8-0' \
    'libpcre2-dev' \
    'libpcre2-posix3' \
    'libsqlite3-dev' \
    'libssl-dev' \
    'libstdc++-12-dev' \
    'libstdc++-13-dev' \
    'libstdc++-14-dev' \
    'libvulkan1' \
    'libwayland-dev' \
    'libx11-xcb-dev' \
    'libxkbcommon-x11-dev' \
    'libzstd-dev' \
    'make' \
    'mold' \
    'musl-dev' \
    'musl-tools' \
    'nasm' \
    'neovim' \
    'ninja-build' \
    'pkg-config' \
    'protobuf-compiler' \
    'python3-dev' \
    'python3-newt' \
    'python3-opencv' \
    'python3-pip' \
    'python3-setuptools' \
    'python3-sphinx' \
    'python3-venv' \
    'squashfs-tools' \
    'unzip' \
    'wget' \
    'yacc' \
    'zip' \
    'zsh' \
    'zstd' \
;
