(global-set-key (kbd "C-;") 'avy-goto-line)
(global-set-key (kbd "C-M-/") #'dabbrev-expand)
(global-set-key (kbd "C-c l") #'myfun/copy-org-src-block )
(global-set-key (kbd "C-h f") #'helpful-callable)
(global-set-key (kbd "C-h k") #'helpful-key)
(global-set-key (kbd "C-h v") #'helpful-variable)
(global-set-key (kbd "C-h x") #'helpful-command)
(global-set-key (kbd "M-/") #'dabbrev-complete)
(key-chord-define-global "6u" 'vundo)
(key-chord-define-global "7u" 'vundo)
(key-chord-define-global "8u" 'vundo)
(key-chord-define-global "[="  'evil-window-split)
(key-chord-define-global "\\=" 'evil-window-split)
(key-chord-define-global "]="  'evil-window-split)
(key-chord-define-global "o="  'evil-window-split)
(key-chord-define-global "p="  'evil-window-split)
(key-chord-define-global "\\'" 'evil-window-vsplit)
(key-chord-define-global "\\;" 'evil-window-vsplit)
(key-chord-define-global "\\[" 'evil-window-vsplit)
(key-chord-define-global "\\]" 'evil-window-vsplit)
(key-chord-define-global "\\l" 'evil-window-vsplit)
(key-chord-define-global "a1" 'counsel-rg)
(key-chord-define-global "a2" 'counsel-rg)
(key-chord-define-global "a`" 'counsel-rg)
(key-chord-define-global "o0" 'hydra-org/body)
(key-chord-define-global "o8" 'hydra-org/body)
(key-chord-define-global "o9" 'hydra-org/body)
(key-chord-define-global "q1" 'hydra-counsel/body)
(key-chord-define-global "q2" 'hydra-counsel/body)
(key-chord-define-global "q`" 'hydra-counsel/body)
(key-chord-define-global "s1" 'swiper)
(key-chord-define-global "s2" 'swiper)
(key-chord-define-global "s3" 'swiper)
(key-chord-define-global "w1" 'myfun/switch_window)
(key-chord-define-global "w2" 'myfun/switch_window)
(key-chord-define-global "w3" 'myfun/switch_window)
(key-chord-define-global "e3" 'counsel-switch-buffer)
(key-chord-define-global "e4" 'counsel-switch-buffer)
(key-chord-define-global "p9" 'hydra-projectile/body)
(key-chord-define-global "p0" 'hydra-projectile/body)
(key-chord-define-global "p-" 'hydra-projectile/body)
(key-chord-define-global "t4" 'hydra-format-and-save/body)
(key-chord-define-global "t5" 'hydra-format-and-save/body)
(key-chord-define-global "t6" 'hydra-format-and-save/body)
