(add-to-list 'load-path (expand-file-name "~/GITHUB/flycheck/flycheck"))



(add-to-list 'load-path (expand-file-name "~/GITHUB/AndreaCrotti/yasnippet-snippets"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/Fanael/rainbow-delimiters"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/Fanael/rainbow-identifiers"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/Wilfred/elisp-refs"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/Wilfred/helpful"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/abo-abo/avy"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/abo-abo/hydra"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/abo-abo/swiper"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/bbatsov/projectile"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/casouri/vundo"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/company-mode/company-mode"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/dgutov/diff-hl"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/emacs-evil/evil"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/emacs-evil/evil-collection"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/emacsmirror/rainbow-mode"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/emacsorphanage/key-chord"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/joaotavora/yasnippet"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/magit/magit/lisp"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/magit/transient/lisp"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/magit/with-editor/lisp"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/magnars/dash.el"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/magnars/s.el"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/noctuid/annalist.el"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/rejeep/f.el"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/tarsius/cond-let"))
(add-to-list 'load-path (expand-file-name "~/GITHUB/tarsius/llama"))
