(setq-default indent-tabs-mode nil)
(setq evil-want-integration t)
(setq evil-want-keybinding nil)
(setq key-chord-two-keys-delay 0.2)
(setq modus-themes-org-blocks 'tinted-background)
(setq org-confirm-babel-evaluate nil)
