#!/bin/sh
exec "$(fd . "${HOME}/scripts/bin" "${HOME}/.nebius/bin" "${HOME}/bin" '/usr/local/sbin' '/usr/local/bin' '/usr/sbin' '/usr/bin' '/sbin' '/bin' '/app/bin' '/var/tmp/flatpak.dir/install/var/lib/flatpak/exports/bin/' | sk)"
exit '0'
