. "${HOME}/.shrc"
export SHELL=zsh
export ZSH="$HOME/.oh-my-zsh"
plugins=(eza fzf git starship vi-mode zoxide zsh-interactive-cd)
source "${ZSH}/oh-my-zsh.sh"
eval "$(atuin init zsh)"
alias cat=bat
alias du=dust
alias top='btm -b'
alias htop='btm -b'
