metadata_dir = "./meta"
data_dir = "./data"

replication_factor = 2
consistency_mode = "consistent"
compression_level = 2

rpc_bind_addr = "[::]:11111"
rpc_public_addr = "#IP#:11111"
rpc_secret = "75a369782e28408900fc674c01c07ddacd40977f509931012809bdff949e8a6a"

bootstrap_peers = []

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:11110"
root_domain = ".s3.garage"

[s3_web]
bind_addr = "[::]:11112"
root_domain = ".web.garage"
index = "index.html"
